repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        name: Check for files that are too large
      - id: trailing-whitespace
        name: Remove all trailing whitespace
      - id: mixed-line-ending
        name: Ensure all line endings are unix-style
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: Ensure all files end with an empty line
      - id: check-yaml
        name: Verify yaml syntax
      - id: check-toml
        name: Verify toml syntax
      - id: check-ast
        name: Verify Python syntax
      - id: name-tests-test
        name: Check that names of test files start with "test_"
        args: [--pytest-test-first]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: Lint Markdown files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: Format GraphQL and JSON files (prettier)
        types_or: [graphql, json]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Python imports (isort)

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        name: Format Python code (black)

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: Check Python docstrings (pydocstyle)
        additional_dependencies: [toml]

  - repo: https://github.com/csachs/pyproject-flake8
    rev: v5.0.4
    hooks:
      - id: pyproject-flake8
        name: Lint Python code (flake8)

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.271
    hooks:
      - id: pyright
        name: Type check Python code (pyright)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Check for Python security issues (bandit)
        args: ["--configfile", "pyproject.toml"]
        additional_dependencies: [toml]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.1
    hooks:
      - id: poetry-check
        name: Verify Poetry configuration
